name: Playwright Tests Prod

on:
  push:
    branches: [ "main" ] # Or your production branch name
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18 # Or your preferred Node.js version
    - name: Install dependencies
      run: npm ci
    - name: Generate Playwright tests (Prod)
      run: NODE_ENV=prod npx bddgen
    - name: Install Playwright browsers (Prod)
      run: npx playwright install chromium
    - name: Run Playwright tests (Prod)
      run: NODE_ENV=prod npx playwright test --project=chromium --workers=3 --retries=2
    - name: Upload Playwright report (Prod)
      uses: actions/upload-artifact@v3 # No change required, but try again.
      if: always()
      with:
        name: playwright-report-prod
        path: playwright-report/